### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by GustavoMilitao** [SwiTool/Dofucks#4]
Hello,

There is any requirements to run WEBGL of Dofucks?

"your device is not supporting WEBGL" is always on screen.

**Comment by SwiTool** [comment]
Hey,

No, you should be able to run it. Please update your video card driver, and then, restart dofucks with `npm run start`.

**Comment by GustavoMilitao** [comment]
I'm here again, 

I haven't any offboard video card, I just have my onboard. 
Does WebGL require offboard video card ?

**Comment by SwiTool** [comment]
No, but update your onboard video card or chipset. What is the brand of
your laptop?

**Comment by GustavoMilitao** [comment]
Actually i'm using a desktop computer.

intel core 2 duo 2.8GHZ, 4 GB RAM, DX12, chipset intel G33/G31 Express (already updated), onboard video card driver igdumd64.dll (OS 64 bits). 

I already activated WEBGL in Chrome but didn't work. I'm dev too, I would like to help improve Dofucks (I love Node.js). I have a bot in C# in my repository and I understood some patterns of message priority strategies that Ankama implements to try to break bots. But I can't start Dofucks, I've got some null reference errors :

`bundle.js:47239 Uncaught TypeError: Cannot read property 'connectionManager' of undefined `
`bundle.js:48274 Uncaught TypeError: Cannot read property 'on' of undefined`
`bundle.js:51886 Uncaught TypeError: Cannot read property 'castSpellMin' of undefined`
`bundle.js:54757 Uncaught TypeError: Cannot read property 'allyRatio' of undefined`

**Comment by SwiTool** [comment]
Do you mean that your only video card is inside the motherboard?
I fear that in this case, webgl or gpu acceleration is not supported by
your hardware.

Please check http://webglreport.com/?v=2 and see if your video card
supports webgl.

**Comment by SwiTool** [comment]
Also, please attach screenshot of screen + console for the errors.
If you have the "this device does not support webGL" screen, i guess it is the default behavior.

**Comment by GustavoMilitao** [comment]
That's the point. I think start module verifies if I can access the bot, when I accessed watch, I could play and use it but wasn't good in graphic.

**Comment by SwiTool** [comment]
Unfortunately we can't lower graphics quality.
Can you play? Is the issue fixed?

**Comment by GustavoMilitao** [comment]
Yes, it was an environment issue. Thanks !
